Repository louvrecly/ab-test-web, pull requests merged in 2020-03, with the labels that each got.

#1 Feat/headnav and recordbutton ui
  .prettierrc
  css/_colors.scss
  css/_media.scss
  css/_typography.scss
  css/main.scss
  public/9up-logo.png
  public/9up-logo.svg
  public/index.html
  src/App.css
  src/App.module.scss
  src/App.tsx
  src/components/DrawerContainer.tsx
  src/components/HeadNav.module.scss
  src/components/HeadNav.tsx
  src/components/RecordButton.module.scss
  src/components/RecordButton.tsx
  src/index.css
  src/index.scss
  src/index.tsx
  src/models/models.tsx
Labels: status: ready for review, type: feature

#2 Enh/add styles to drawer
  package.json
  src/components/DrawerContainer.module.scss
  src/components/DrawerContainer.tsx
  yarn.lock
Labels: status: ready for review, type: enhancement

#3 Feat/headnav and recordbutton ui
  package.json
  src/components/DrawerContainer.module.scss
  src/components/DrawerContainer.tsx
  yarn.lock
Labels: status: ready to merge

#5 Feat/leaflet map
  package.json
  public/index.html
  src/App.module.scss
  src/App.tsx
  src/components/DrawerContainer/DrawerContainer.module.scss
  src/components/DrawerContainer/index.tsx
  src/components/HeadNav/HeadNav.module.scss
  src/components/HeadNav/index.tsx
  src/components/Map.tsx
  src/components/RecordButton/RecordButton.module.scss
  src/components/RecordButton/index.tsx
  yarn.lock
Labels: status: ready for review, type: feature

#6 Enh/leaflet map styles
  src/App.module.scss
  src/components/DrawerContainer/DrawerContainer.module.scss
  src/components/Map.tsx
  src/components/Map/Map.module.scss
  src/components/Map/constant.ts
  src/components/Map/index.tsx
Labels: status: ready for review, type: enhancement

#7 Enh/absolute import
  src/App.tsx
  src/components/DrawerContainer/index.tsx
  src/components/DrawerContainer/styles.module.scss
  src/components/HeadNav/index.tsx
  src/components/HeadNav/styles.module.scss
  src/components/Map/index.tsx
  src/components/Map/styles.module.scss
  src/components/RecordButton/index.tsx
  src/components/RecordButton/styles.module.scss
  src/models/index.tsx
  tsconfig.json
  tslint.json
Labels: help wanted, status: ready for review, type: enhancement

#8 Feat/redux store threads
  .env.example
  .gitignore
  package.json
  src/App.module.scss
  src/App.tsx
  src/components/Main/index.tsx
  src/components/Main/styles.module.scss
  src/components/Map/index.tsx
  src/components/Map/styles.module.scss
  src/index.tsx
  src/models/index.tsx
  src/redux/threads/actions.ts
  src/redux/threads/reducer.ts
  src/redux/threads/state.ts
  src/redux/threads/thunks.ts
  src/store.ts
  tslint.json
  yarn.lock
Labels: status: ready for review, type: feature

#9 Enh/absolute import
  .env.example
  .gitignore
  package.json
  src/App.module.scss
  src/App.tsx
  src/components/Main/index.tsx
  src/components/Main/styles.module.scss
  src/components/Map/index.tsx
  src/components/Map/styles.module.scss
  src/index.tsx
  src/models/index.tsx
  src/redux/threads/actions.ts
  src/redux/threads/reducer.ts
  src/redux/threads/state.ts
  src/redux/threads/thunks.ts
  src/store.ts
  tslint.json
  yarn.lock
Labels: status: ready to merge, type: enhancement

#11 Fix/replace firebase admin with firebase
  package.json
  src/models/index.tsx
  yarn.lock
Labels: status: ready for review, type: bug

#10 Feat/redux store active thread
  package.json
  src/components/DrawerContainer/index.tsx
  src/components/DrawerContainer/styles.module.scss
  src/components/HeadNav/index.tsx
  src/components/Main/index.tsx
  src/components/Main/styles.module.scss
  src/components/Map/constant.ts
  src/components/Map/index.tsx
  src/components/Map/styles.module.scss
  src/components/ThreadPanel/index.tsx
  src/components/ThreadPanel/styles.module.scss
  src/models/index.tsx
  src/redux/components/actions.ts
  src/redux/components/reducer.ts
  src/redux/components/state.ts
  src/redux/threads/actions.ts
  src/redux/threads/reducer.ts
  src/redux/threads/state.ts
  src/store.ts
  yarn.lock
Labels: status: ready for review, type: feature

#12 Enh/replace classnames with clsx
  package.json
  src/components/DrawerContainer/index.tsx
  yarn.lock
Labels: status: ready for review, type: enhancement

#13 Enh/react icons
  package.json
  src/components/HeadNav/index.tsx
  src/components/HeadNav/styles.module.scss
  src/components/ThreadPanel/index.tsx
  src/components/ThreadPanel/styles.module.scss
  yarn.lock
Labels: status: ready for review, type: enhancement
